import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import productsRouter from "./products";
import categoriesRouter from "./categories";
import cartRouter from "./cart";
import wishlistRouter from "./wishlist";
import ordersRouter from "./orders";
import reviewsRouter from "./reviews";
import newsletterRouter from "./newsletter";
import paymentsRouter from "./payments";
import postsRouter from "./posts";
import seedRouter from "./seed";
import channelsRouter from "./channels";
import facebookRouter from "./facebook";
import whatsappRouter from "./whatsapp";
import twitterRouter from "./twitter";
import usersRouter from "./users";
import settingsRouter from "./settings";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/products", productsRouter);
router.use("/categories", categoriesRouter);
router.use("/cart", cartRouter);
router.use("/wishlist", wishlistRouter);
router.use("/orders", ordersRouter);
router.use("/reviews", reviewsRouter);
router.use("/newsletter", newsletterRouter);
router.use("/payments", paymentsRouter);
router.use("/posts", postsRouter);
router.use("/seed", seedRouter);
router.use("/channels", channelsRouter);
router.use("/facebook", facebookRouter);
router.use("/whatsapp", whatsappRouter);
router.use("/twitter", twitterRouter);
router.use("/users", usersRouter);
router.use("/settings", settingsRouter);

export default router;
